title: "0xrwise - Researcher"
name:  "0xrwise"
description: "Research, Reflect, Wisdom."
url: "https://yourdomain.com"
author:
  name: "0xrwise"

# Enables dark/light toggle button in nav
javascript_enabled: true


# Collections
collections:
  news:
    output: true
    title: News
    default_open: false
  essays:
    output: true
    title: Essays
    default_open: true

# Default front matter
defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "essays"
    values:
      layout: "post"

sass:
  style: compressed
  quiet_deps: true
  
plugins:
  - jekyll-feed

permalink: /:collection/:title

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
